server.port=8084
spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
user.service.url=http://user-service:8080/users
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yml